name: Auto Comment

on: [pull_request]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: wow-actions/auto-comment@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                  pullRequestedReadyForReview: |
                      Hello reviewers! Before approving this PR, please ensure the following:

                        - [ ] Documentation is up to date
                        - [ ] Relevent tutorials are up to date
                        - [ ] Changelog is up to date
                        - [ ] Test coverage is at 100%
                        - [ ] All checks are passing
                        - [ ] That the new code actually works

                      Once all this is done, you can be sure that the PR is ready to be merged. 🎉
