name: Build

on: [push]

jobs:
    test-linux:
        name: ${{ matrix.name-prefix }}${{ matrix.python-version }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10"]
                name-prefix: ["Linux (Python"]

        env:
            SDL_VIDEODRIVER: dummy
            SDL_AUDIODRIVER: dummy
            SDL_RENDER_DRIVER: software
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev] pysdl2-dll

            - name: Run Unit Tests
              run: pytest --cov=rubato rubato/tests

    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]

            - name: Analysing the code with pylint
              run: pylint $(git ls-files 'rubato/**/*.py')
