name: Build

on: [push]

jobs:
    test:
        name: ${{ matrix.os }} (Python ${{ matrix.python-version }})
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10"]
                os: ["ubuntu-latest", "macos-latest", "windows-latest"]

        env:
            SDL_VIDEODRIVER: dummy
            SDL_AUDIODRIVER: dummy
            SDL_RENDER_DRIVER: software
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]

            - if: startsWith(matrix.os, 'ubuntu')
              name: Install SDL
              run: pip install pysdl2-dll
            - if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'windows')
              name: Install SDL
              run: git submodule update --init --recursive

            - name: Run Unit Tests
              run: pytest --cov=rubato rubato/tests

    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]

            - name: Analysing the code with pylint
              run: pylint $(git ls-files 'rubato/**/*.py')
