name: Build Documentation

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev libjpeg-dev python3-setuptools python3-dev python3-numpy
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: build docs
              run: cd docs && make html && cd ..
              
            - name: GitHub Commit & Push with Rebase
              # You may pin to the exact commit or the version.
              # uses: benkaiser/rebase-commit-push@2e4425afdbe0e3573d7c75ae76947d99a85117a3
              uses: benkaiser/rebase-commit-push@v1.1
              with:
                # Commit message.
                message: build documentation
                # Destination branch to push changes
                branch: main
                # Allow empty commit
                empty: true
