name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
#                  sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev libjpeg-dev python3-setuptools python3-dev python3-numpy
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Analysing the code with pylint
              run: pylint $(git ls-files '*.py')

            # - name: Run test file
            #   run: python test.py
