name: Docs Preview Build

on:
    push:
        branches-ignore:
            - "main"

concurrency:
    cancel-in-progress: true
    group: preview-${{ github.ref }}

jobs:
    docs:
        name: Build Docs
        runs-on: ubuntu-latest
        env:
            RUBATO_VERSION: "v0.0.0"
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install Cython==3.0.0a11 --install-option="--no-cython-compile"
                  python setup.py egg_info
                  pip install `grep -v '^\[' rubato.egg-info/requires.txt`

            - name: Build Docs
              run: make docs-save

            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v1.2
              with:
                  publish-dir: "./docs/build/html"
                  production-branch: main
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  deploy-message: "Deploy from GitHub Actions"
                  enable-pull-request-comment: true
                  enable-commit-comment: false
                  overwrites-pull-request-comment: true
                  alias: ${{ github.head_ref }}
                  github-deployment-environment: Preview-${{ github.head_ref }}
                  github-deployment-description: "Preview build for ${{ github.head_ref }}"
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1
