name: Docs Preview Build

on:
    push:
        branches-ignore:
            - "main"

concurrency:
    cancel-in-progress: true
    group: preview-${{ github.ref }}

jobs:
    docs:
        name: Build Docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

            - uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install Cython==3.0.0a10 --install-option="--no-cython-compile"
                  python setup.py egg_info
                  pip install `grep -v '^\[' rubato.egg-info/requires.txt`

            - name: Build Docs
              run: |
                  (cd docs && make save)
                  cp -r docs/build/html docs/temp

            - name: Commit files
              run: |
                  git config --local user.email "martin.chapino@gmail.com"
                  git config --local user.name "Martin Chaperot [bot]"
                  git commit -m "Build Docs" -a

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
