name: Docs

on: [push, pull_request]

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev libjpeg-dev python3-setuptools python3-dev python3-numpy
                  pip install -r requirements.txt

            - name: Build the sphinx documentation and posts warnings as github comments.
                  uses: rickstaa/sphinx-action@master
                  with:
                    docs-folder: "./docs"

            - name: Commit files
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git commit -m "Add changes" -a

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
