name: Manually Publish to PyPi

on:
    workflow_dispatch:
        inputs:
            versionNumber:
                required: true
                type: string
                description: Version Number (ex. 1.2.3.dev4)

jobs:
    publisher:
        name: Publish to PyPi
        runs-on: ubuntu-latest
        env:
            RUBATO_VERSION: ${{ inputs.versionNumber }}
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  pip install build Cython~=3.0.0a11

            - name: Build
              run: python -m setup sdist --formats zip

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
