name: Manually Publish to TestPyPi

on:
    workflow_dispatch:
        inputs:
            versionNumber:
                required: true
                type: string
                description: Version Number (ex. 1.2.3.dev4)

jobs:
    publisher:
        name: Publish to PyPi
        runs-on: ubuntu-latest
        env:
            RUBATO_VERSION: ${{ inputs.versionNumber }}
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  git submodule update --init --recursive
                  pip install Cython==3.0.0a11 --install-option="--no-cython-compile"
                  python setup.py egg_info
                  pip install `grep -v '^\[' rubato.egg-info/requires.txt`
                  pip install build twine

            - name: Build
              run: python -m build && rm -rf **/*.whl

            - name: Publish to TestPyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                  repository_url: https://test.pypi.org/legacy/
