name: Nightly Build

on:
    workflow_dispatch:
    push:
        branches:
            - "main"

jobs:
    docs:
        runs-on: ubuntu-latest
        env:
            RUBATO_VERSION: "v0.0.0"
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install Cython==3.0.0a10
                  python setup.py egg_info
                  pip install `grep -v '^\[' rubato.egg-info/requires.txt`
                  make delete-build

            - name: Build Docs
              run: make docs-save

            - name: Prep files for transfer
              run: |
                  cp -r docs/build/html nightly
                  cp docs/index.html index.html
                  cp docs/404.html 404.html
                  cp docs/sitemap_gen.py sitemap_gen.py

            - name: Prep Git
              run: |
                  git config --global user.email "martin.chapino@gmail.com"
                  git config --global user.name "Martin Chaperot (Bot)"

            - name: Transfer to rubato.app
              run: |
                  rm -rf target
                  git clone https://.:${{ secrets.MY_GITHUB_TOKEN }}@github.com/rubatopy/rubato.app.git target
                  cp index.html 404.html sitemap_gen.py target
                  cd target
                  git add .
                  git diff-index --quiet HEAD || git commit -m "Update from ${{ github.sha }}"
                  git push origin main

            - name: Transfer to docs.rubato.app
              run: |
                  rm -rf target
                  git clone https://.:${{ secrets.MY_GITHUB_TOKEN }}@github.com/rubatopy/docs.rubato.app.git target
                  cp -R nightly sitemap_gen.py target
                  cd target
                  git add .
                  git diff-index --quiet HEAD || git commit -m "Update from ${{ github.sha }}"
                  git push origin main
