name: Nightly Build

on:
    workflow_dispatch:
    push:
        branches:
            - "main"

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

            - uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[docs]

            - name: Build Docs
              run: (cd docs && make save)

            - name: Prep files for transfer
              run: |
                  cp -r docs/build/html nightly
                  cp docs/index.html index.html
                  cp docs/404.html 404.html
                  cp docs/sitemap_gen.py sitemap_gen.py

            - name: Transfer to rubato.app
              uses: dmnemec/copy_file_to_another_repo_action@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
              with:
                  source_file: "index.html 404.html sitemap_gen.py"
                  destination_repo: "rubatopy/rubato.app"
                  user_email: "martin.chapino@gmail.com"
                  user_name: "Martin"
                  commit_message: "Update according to rubato commit ${{ github.sha }}"

            - name: Transfer to docs.rubato.app
              uses: dmnemec/copy_file_to_another_repo_action@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
              with:
                  source_file: "nightly/ sitemap_gen.py"
                  destination_repo: "rubatopy/docs.rubato.app"
                  user_email: "martin.chapino@gmail.com"
                  user_name: "Martin"
                  commit_message: "Update according to rubato commit ${{ github.sha }}"
