name: Auto Assign to Project(s)

on:
    issues:
        types: [opened]
    pull_request:
        types: [review_requested]

env:
    MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
    assign_one_project:
        runs-on: ubuntu-latest
        name: Assign to One Project
        steps:
            - name: Assign new issues to project
              uses: srggrs/assign-one-project-github-action@1.3.1
              if: github.event_name == 'issues'
              with:
                  project: "https://github.com/orgs/rubatopy/projects/4"
                  column_name: "Backlog"

            - name: Assign new pull requests to project
              uses: srggrs/assign-one-project-github-action@1.3.1
              if: github.event_name == 'pull_request'
              with:
                  project: "https://github.com/orgs/rubatopy/projects/4"
                  column_name: "In Review"
