name: Release

on:
    release:
        types: [published]

jobs:
    builder:
        name: Build ${{ matrix.os }} (Python ${{ matrix.python-version }})
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10"]
                os: ["windows-latest", "macos-latest"]

        steps:
            - name: Report Version
              run: |
                  export RUBATO_VERSION=${{ github.ref_name }}
                  echo "Releasing $RUBATO_VERSION"
              shell: bash

            - name: cancelling
              if: ${{ !contains(github.ref_name, 'v' ) }}
              uses: andymckay/cancel-action@0.2

            - uses: actions/checkout@v3
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install requirements
              run: |
                  pip install --upgrade pip
                  git submodule update --init --recursive
                  pip install build

            - name: Build
              run: RUBATO_VERSION=${{ github.ref_name }} python -m build
              shell: bash

            - name: Upload Wheel as Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: ${{matrix.os}}-wheel
                  path: dist/*.whl

            - name: Upload Wheel as Artifact
              if: startsWith(matrix.os, 'windows')
              uses: actions/upload-artifact@v3
              with:
                  name: tar.gz
                  path: dist/*.tar.gz

    releaser:
        name: Release ${{github.ref_name}}
        runs-on: ubuntu-latest
        needs: builder
        steps:
            - uses: actions/download-artifact@v3

            - name: Display structure of downloaded files
              run: ls -R

            # - name: Publish to PyPI
            #   uses: pypa/gh-action-pypi-publish@release/v1
            #   with:
            #       user: __token__
            #       password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            #       repository_url: https://test.pypi.org/legacy/
