name: Test Suite

on: [push]

jobs:
    demo:
        name: Test Demo Files
        runs-on: ubuntu-latest
        env:
            SDL_VIDEODRIVER: dummy
            SDL_AUDIODRIVER: dummy
            SDL_RENDER_DRIVER: software
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pysdl2-dll
                  pip install .[dev]

            - name: Run Demos
              run: |
                  cd demo
                  ./_run_all.sh
    unittest:
        name: ${{ matrix.os }} (Python ${{ matrix.python-version }})
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10", "3.11.0rc1"]
                os: ["ubuntu-latest", "windows-latest"]

        env:
            SDL_VIDEODRIVER: dummy
            SDL_AUDIODRIVER: dummy
            SDL_RENDER_DRIVER: software
            RUBATO_VERSION: "v0.0.0"
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Prep setup
              run: |
                  python -m pip install --upgrade pip
                  pip install Cython==3.0.0a11 --install-option="--no-cython-compile"
                  pip install -e .[dev]
              shell: bash

            - name: Run Unit Tests
              run: ./b test

    lint:
        name: Lint Code
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install Cython==3.0.0a11 --install-option="--no-cython-compile"
                  python setup.py egg_info
                  pip install `grep -v '^\[' rubato.egg-info/requires.txt`

            - name: Analysing the code with pylint
              run: pylint rubato
